function alpha_c = alpha_c(F2,p_a,rho_0,acoustic_f)
%ALPHA_C
%    ALPHA_C = ALPHA_C(F2,P_A,RHO_0,ACOUSTIC_F)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    19-Apr-2020 19:34:28

alpha_c = (F2.*1.0./acoustic_f.^2.*p_a.^2.*(1.0./4.0))./(rho_0.*pi);
