function C_d = C_d(Re)
%C_D
%    C_D = C_D(RE)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    19-Apr-2020 19:34:30

C_d = (Re.*2.5e-7)./(Re.*1.0e-6+1.0)+(Re.*(1.3e1./2.5e1))./((Re.*(1.0./5.0)).^(3.8e1./2.5e1)+1.0)+(1.0./(Re.*3.802281368821293e-6).^(3.97e2./5.0e1).*(4.11e2./1.0e3))./(1.0./Re.^8.*2.289001029054101e43+1.0)+2.4e1./Re;
