function F_gravity_buoyancy = F_gravity_buoyancy(r,rho_p,rho_0)
%F_GRAVITY_BUOYANCY
%    F_GRAVITY_BUOYANCY = F_GRAVITY_BUOYANCY(R,RHO_P,RHO_0)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    19-Apr-2020 19:34:28

t2 = r.^2;
F_gravity_buoyancy = -abs(r.*rho_0.*t2.*pi.*(3.27e2./2.5e1)-r.*rho_p.*t2.*pi.*(3.27e2./2.5e1));
