function mass = mass(r,rho_p)
%MASS
%    MASS = MASS(R,RHO_P)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    19-Apr-2020 19:34:29

t2 = r.^2;
mass = r.*rho_p.*t2.*pi.*(4.0./3.0);
