function Re = Reynolds(r,rho_0,vel_z,visc)
%REYNOLDS
%    RE = REYNOLDS(R,RHO_0,VEL_Z,VISC)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    19-Apr-2020 19:34:28

Re = (r.*rho_0.*vel_z.*2.0)./visc;
