function virtual_mass = virtual_mass(r,rho_0)
%VIRTUAL_MASS
%    VIRTUAL_MASS = VIRTUAL_MASS(R,RHO_0)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    19-Apr-2020 19:34:28

t2 = r.^2;
virtual_mass = r.*rho_0.*t2.*pi.*(2.0./3.0);
